import { ethers } from "ethers";
import * as snarkjs from "snarkjs";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Verification keys (generated by build.sh) ─────────────────────────────────
const VKEYS = {
  age_over_18:   loadVKey("age_over_18"),
  valid_license: loadVKey("valid_license"),
  residency:     loadVKey("residency"),
};

function loadVKey(circuitName) {
  try {
    const path = join(__dirname, `../../../circuits/build/${circuitName}/verification_key.json`);
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    console.warn(`[zkVerifier] Verification key not found for ${circuitName} — using mock mode`);
    return null;
  }
}

// ── Blockchain provider ───────────────────────────────────────────────────────
const provider = new ethers.JsonRpcProvider(
  process.env.RPC_URL || "https://rpc.cardona.zkevm-rpc.com"
);

const REGISTRY_ABI = [
  "function isNullifierUsed(bytes32) view returns (bool)",
  "function getBatchRoot(address, uint256) view returns (bytes32)",
];

const VERIFIER_ABI = [
  "function verifyProofOnly(uint8, uint256[2], uint256[2][2], uint256[2], uint256[]) view returns (bool)",
];

function getRegistry() {
  const addr = process.env.CREDENTIAL_REGISTRY_ADDRESS;
  if (!addr) throw new Error("CREDENTIAL_REGISTRY_ADDRESS not set");
  return new ethers.Contract(addr, REGISTRY_ABI, provider);
}

function getVerifierContract() {
  const addr = process.env.VERIFIER_CONTRACT_ADDRESS;
  if (!addr) throw new Error("VERIFIER_CONTRACT_ADDRESS not set");
  return new ethers.Contract(addr, VERIFIER_ABI, provider);
}

// ── Core verification logic ───────────────────────────────────────────────────
/**
 * Verify a ZK proof off-chain (gasless for the user).
 *
 * Steps:
 * 1. Verify the Groth16 proof locally with SnarkJS.
 * 2. Check the Merkle root is registered on-chain.
 * 3. Check the nullifier hasn't been used (anti-replay).
 *
 * @param {string} claimType  - "age_over_18" | "valid_license" | "residency"
 * @param {object} proof      - { pi_a, pi_b, pi_c, publicSignals }
 * @param {string} issuer     - Ethereum address of the issuer
 * @param {number} batchId    - Batch ID in the registry
 */
export async function verifyZKProof({ claimType, proof, issuer, batchId }) {
  const { pi_a, pi_b, pi_c, publicSignals } = proof;

  // ── 1. Local Groth16 verification (no gas, instant) ──────────────────────
  const vkey = VKEYS[claimType];
  if (!vkey) {
    // Dev mode: skip ZK verification if keys not compiled yet
    console.warn(`[zkVerifier] MOCK MODE — skipping ZK verification for ${claimType}`);
    return { valid: true, mock: true, nullifier: publicSignals[1] };
  }

  const proofValid = await snarkjs.groth16.verify(vkey, publicSignals, {
    pi_a, pi_b, pi_c,
  });

  if (!proofValid) {
    return { valid: false, reason: "Invalid ZK proof" };
  }

  // ── 2. On-chain: check Merkle root is registered ──────────────────────────
  const merkleRoot = publicSignals[0];
  const nullifier  = publicSignals[1];

  try {
    const registry = getRegistry();

    const registeredRoot = await registry.getBatchRoot(issuer, batchId);
    if (registeredRoot === ethers.ZeroHash) {
      return { valid: false, reason: "Batch not found on-chain" };
    }

    const rootHex = "0x" + BigInt(merkleRoot).toString(16).padStart(64, "0");
    if (registeredRoot.toLowerCase() !== rootHex.toLowerCase()) {
      return { valid: false, reason: "Merkle root mismatch" };
    }

    // ── 3. On-chain: check nullifier not used ─────────────────────────────
    const nullifierHex = "0x" + BigInt(nullifier).toString(16).padStart(64, "0");
    const isUsed = await registry.isNullifierUsed(nullifierHex);
    if (isUsed) {
      return { valid: false, reason: "QR already used (nullifier consumed)" };
    }

    return {
      valid: true,
      nullifier: nullifierHex,
      merkleRoot: rootHex,
      claimType,
    };
  } catch (err) {
    console.error("[zkVerifier] Blockchain check failed:", err.message);
    // Fallback: return ZK-only result if blockchain is unreachable
    return {
      valid: true,
      nullifier: "0x" + BigInt(nullifier).toString(16).padStart(64, "0"),
      claimType,
      warning: "Blockchain check skipped (RPC unavailable)",
    };
  }
}

/**
 * Build the input object for a ZK proof generation (called from the mobile app).
 * This runs on the user's device via SnarkJS WASM.
 */
export function buildProofInput({ claimType, credentialData, merkleProof, currentDate }) {
  const { year, month, day } = currentDate;

  const base = {
    credentialSecret: credentialData.secret,
    merklePathElements: merkleProof.pathElements,
    merklePathIndices: merkleProof.pathIndices,
    merkleRoot: merkleProof.root,
    currentYear: year,
    currentMonth: month,
    currentDay: day,
  };

  switch (claimType) {
    case "age_over_18":
      return {
        ...base,
        birthYear:  credentialData.birthYear,
        birthMonth: credentialData.birthMonth,
        birthDay:   credentialData.birthDay,
      };

    case "valid_license":
      return {
        ...base,
        expiryYear:       credentialData.expiryYear,
        expiryMonth:      credentialData.expiryMonth,
        licenseCategory:  credentialData.licenseCategory || 2, // B = 2
        requiredCategory: 0,
      };

    case "residency":
      return {
        ...base,
        countryCode:         credentialData.countryCode,
        regionCode:          credentialData.regionCode || 0,
        requiredCountryCode: credentialData.countryCode,
        requiredRegionCode:  0,
      };

    default:
      throw new Error(`Unknown claim type: ${claimType}`);
  }
}
